"""Generate a DVC pipeline (``dvc.yaml``) for the YOLO train/eval loop.

cv_lib does **not** depend on DVC — this module only scaffolds a ``dvc.yaml``
(and an optional ``params.yaml``) that wires ``cvlib`` subcommands into
reproducible stages. The result is a starting point: edit the paths and commands
to match your dataset layout, then ``pip install dvc`` and ``dvc repro``.

Standard stages (issue #3)::

    collect → split → train (external) → compare-with-prev → report

- **collect** — convert raw annotations (CVAT/COCO) to YOLO labels (``cvlib convert``).
- **split** — train/val/test split + ``data.yaml`` (``cvlib split``).
- **train** — your own training module; hyper-params live in ``params.yaml``.
- **compare-with-prev** — diff the new run against previous ones (``cvlib compare-runs``).
- **report** — eval the best checkpoint, write a confusion matrix (``cvlib eval``).
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Any

import yaml

# Canonical stage order. build_pipeline() always emits stages in this order.
STAGES: tuple[str, ...] = ("collect", "split", "train", "compare-with-prev", "report")

_DVC_HEADER = (
    "# Generated by `cvlib dvc-init` — a scaffold, not magic.\n"
    "# Edit paths/commands to match your dataset, then `pip install dvc && dvc repro`.\n"
    "# cv_lib does not depend on DVC; install it separately.\n"
    "# Stages: collect -> split -> train -> compare-with-prev -> report\n\n"
)

_PARAMS_HEADER = (
    "# Training hyper-parameters tracked by DVC (referenced from the `train` stage).\n"
    "# Changing a value here invalidates the train stage on the next `dvc repro`.\n\n"
)


@dataclass(frozen=True)
class PipelineConfig:
    """Paths and commands the generated ``dvc.yaml`` is built from."""

    annotations: str = "data/raw/annotations.xml"
    images_dir: str = "data/images"
    labels_dir: str = "data/labels"
    dataset_dir: str = "data/dataset"
    data_yaml: str = "data/dataset/data.yaml"
    runs_root: str = "runs/train"
    run_name: str = "exp"
    train_cmd: str = "python train.py --data data/dataset/data.yaml --project runs/train --name exp"
    cm_out: str = "reports/confusion_matrix.png"

    @property
    def run_dir(self) -> str:
        return f"{self.runs_root}/{self.run_name}"


def _stage_collect(c: PipelineConfig) -> dict[str, Any]:
    return {
        "cmd": f"cvlib convert {c.annotations} --out {c.labels_dir}",
        "deps": [c.annotations],
        "outs": [c.labels_dir],
    }


def _stage_split(c: PipelineConfig) -> dict[str, Any]:
    return {
        "cmd": f"cvlib split {c.images_dir} --labels {c.labels_dir} --out {c.dataset_dir}",
        "deps": [c.images_dir, c.labels_dir],
        "outs": [c.dataset_dir],
    }


def _stage_train(c: PipelineConfig) -> dict[str, Any]:
    return {
        "cmd": c.train_cmd,
        "deps": [c.dataset_dir, c.data_yaml],
        "params": ["train"],
        "outs": [c.run_dir],
    }


def _stage_compare_with_prev(c: PipelineConfig) -> dict[str, Any]:
    return {
        "cmd": f"cvlib compare-runs {c.runs_root}",
        "deps": [c.run_dir],
        # Comparison reads sibling runs that DVC doesn't track as deps.
        "always_changed": True,
    }


def _stage_report(c: PipelineConfig) -> dict[str, Any]:
    return {
        "cmd": (
            f"cvlib eval --model {c.run_dir}/weights/best.pt "
            f"--data {c.data_yaml} --cm-out {c.cm_out}"
        ),
        "deps": [f"{c.run_dir}/weights/best.pt", c.data_yaml],
        "outs": [c.cm_out],
    }


_BUILDERS = {
    "collect": _stage_collect,
    "split": _stage_split,
    "train": _stage_train,
    "compare-with-prev": _stage_compare_with_prev,
    "report": _stage_report,
}


def build_pipeline(
    config: PipelineConfig | None = None,
    stages: tuple[str, ...] | list[str] = STAGES,
) -> dict[str, Any]:
    """Build the ``dvc.yaml`` document (``{"stages": {...}}``) as a plain dict.

    ``stages`` selects a subset; the output always follows the canonical
    :data:`STAGES` order regardless of the order requested.
    """
    config = config or PipelineConfig()
    selected = set(stages)
    unknown = selected - set(_BUILDERS)
    if unknown:
        raise ValueError(f"Unknown stage(s): {sorted(unknown)}. Valid: {list(STAGES)}")
    return {"stages": {s: _BUILDERS[s](config) for s in STAGES if s in selected}}


def default_params() -> dict[str, Any]:
    """Default ``params.yaml`` content (the ``train`` group used by the train stage)."""
    return {
        "train": {
            "model": "yolov8n.pt",
            "epochs": 100,
            "imgsz": 640,
            "batch": 16,
            "seed": 42,
        }
    }


def _write_yaml(out_path: str | Path, data: dict[str, Any], header: str, force: bool) -> Path:
    out = Path(out_path)
    if out.exists() and not force:
        raise FileExistsError(f"{out} already exists (pass force=True / --force to overwrite).")
    if out.parent != Path():
        out.parent.mkdir(parents=True, exist_ok=True)
    # width=inf keeps long `cmd` strings on one line instead of folding them.
    body = yaml.safe_dump(data, sort_keys=False, default_flow_style=False, width=float("inf"))
    out.write_text(header + body, encoding="utf-8")
    return out


def generate_dvc_yaml(
    out_path: str | Path = "dvc.yaml",
    *,
    config: PipelineConfig | None = None,
    stages: tuple[str, ...] | list[str] = STAGES,
    force: bool = False,
) -> Path:
    """Write a ``dvc.yaml`` scaffold to ``out_path``. Returns the written path."""
    pipeline = build_pipeline(config, stages)
    return _write_yaml(out_path, pipeline, _DVC_HEADER, force)


def generate_params_yaml(out_path: str | Path = "params.yaml", *, force: bool = False) -> Path:
    """Write a ``params.yaml`` scaffold (``train`` hyper-params). Returns the path."""
    return _write_yaml(out_path, default_params(), _PARAMS_HEADER, force)
